### ISSUE TITLE
syntax error in python code?

### ISSUE THREAD

**Issue by khaoohs** [sky-cake/Ritual#2]
https://github.com/sky-cake/Ritual/blob/242add3ac67a0f121df29d08b73400e0aedf0c1a/main.py#L242
https://github.com/sky-cake/Ritual/blob/242add3ac67a0f121df29d08b73400e0aedf0c1a/main.py#L247

python3 main.py
Traceback (most recent call last):
  File "/home/khaoohs/src/Ritual/main.py", line 242, in <module>
    def get_fs_filename_full_media(post: dict) -> str|None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by sky-cake** [comment]
@khaoohs I believe the union operator is a 3.10 or later feature

https://peps.python.org/pep-0604/

**Comment by sky-cake** [comment]
Removed union type hints, as they aren't important.
